# Generated by Django 4.2.17 on 2025-07-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0002_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('artcile', 'Article'), ('educational', 'Educational'), ('announcement', 'Announcement')], default='artcile', max_length=20),
        ),
    ]
