---
deployment:
  tasks:
    # Set paths
    - export REPO_DIR=/home/karencar/repositories/ClinicFinal
    - export APP_DIR=/home/karencar/Python_Host
    - export DJANGO_SETTINGS_MODULE=Clinic.settings

    # Copy updated code to app directory (delete old files first for clean sync)
    - rm -rf $APP_DIR/*
    - cp -R $REPO_DIR/* $APP_DIR/

    # Activate virtualenv
    - source /home/karencar/virtualenv/Python_Host/3.12/bin/activate

    # Install/update Python packages
    - cd $APP_DIR
    - pip install -r requirements.txt

    # Collect static files
    - python manage.py collectstatic --noinput
